### ISSUE TITLE
Rent cars page

### ISSUE THREAD

**Issue by ashenafykebede** [lab-antwerp-1/agile-group-4#11]
### Tasks to be accomplished

- **Rent cars page**
    - [x] Backlog
    - [x] Development strategy
    - [x] HTML
    - [x] CSS
 - **Code quality checks**
    - [ ]  All designs passed  _**npm run format**_
    - [ ]  All designs passed _**npm run lint:md**_
    - [ ]  All designs passed _**npm run lint:css**_
    - [ ]  All designs passed _**npm run validate:html -- ./path/to/file.html**_
    - [ ]  All designs passed _**npm run spell-check**_
    - [ ]  All designs passed _**npm run accessibility -- ./path/to/file.html**_
