### ISSUE TITLE
Car models

### ISSUE THREAD

**Issue by ashenafykebede** [lab-antwerp-1/agile-group-4#12]
### Tasks to be accomplished

- **Our partners / Car models page**
    - [ ] Backlog
    - [ ] Development strategy
    - [ ] HTML
    - [ ] CSS
 - **Code quality checks**
    - [ ]  All designs passed  _**npm run format**_
    - [ ]  All designs passed _**npm run lint:md**_
    - [ ]  All designs passed _**npm run lint:css**_
    - [ ]  All designs passed _**npm run validate:html -- ./path/to/file.html**_
    - [ ]  All designs passed _**npm run spell-check**_
    - [ ]  All designs passed _**npm run accessibility -- ./path/to/file.html**_
