### ISSUE TITLE
About us page

### ISSUE THREAD

**Issue by ashenafykebede** [lab-antwerp-1/agile-group-4#8]
### Tasks to be accomplished

- **About us**
    - [ ] Backlog
    - [ ] Development strategy
    - [ ] HTML
    - [ ] CSS
 - **Check**
    - [ ]  All designs passed  _**npm run format**_
    - [ ]  All designs passed _**npm run lint:md**_
    - [ ]  All designs passed _**npm run lint:css**_
    - [ ]  All designs passed _**npm run validate:html -- ./path/to/file.html**_
    - [ ]  All designs passed _**npm run spell-check**_
    - [ ]  All designs passed _**npm run accessibility -- ./path/to/file.html**_
